name: Build Unity APK on Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python (for asset download)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install gdown
        run: pip install gdown

      # Step 3: Download your models/videos using your script
      - name: Download External Assets
        run: python Scripts/download_assets.py

      # Step 4: Cache Unity Library to speed up future builds
      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/*.cs') }}
          restore-keys: |
            Library-${{ runner.os }}-

      # Step 5: Build the project using game-ci/unity-builder
      - name: Build APK
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.0f1  # replace with your exact Unity version
          targetPlatform: Android
          buildPath: Builds/Android

      # Step 6: Upload built APK to GitHub Releases
      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: Builds/Android/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
